name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install requirements
        run: pip install -r build/requirements.txt

      - name: Build
        run: pyinstaller --onefile mixxx_metadata_retriever.py

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: mixxx_metadata_retriever-v-${{ matrix.os }}
          path: dist/*
